[package]
name = "wasm-mora-counter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2.17", features = ["js"] }
vibrato = "0.5.2"
wasm-bindgen = "0.2.108"
